Repository Step3-kakao-tech-campus/Team3_FE, pull requests merged in 2023-11, with the labels that each got.

#77 [Feat] 마이 페이지 UI 및 기능 구현
  src/apis/district.ts
  src/apis/profile.ts
  src/app/mypage/loading.tsx
  src/app/mypage/page.tsx
  src/components/templates/MyPageTemplate/index.tsx
  src/components/templates/ProfileModalTemplate/index.tsx
  src/components/templates/ScoreEditTemplate/index.tsx
  src/hooks/useMounted.ts
Labels: Priority: Medium, Type: Enhancement

#78 [Fix] 스코어 보드 페이지 검색 바 기능 수정
  src/components/molecules/RecordSearchBar/index.tsx
  src/components/molecules/SimpleDatePicker/index.tsx
Labels: Priority: Low, Type: Bug

#80 [Fix] 이미지 버그 수정
  next.config.js
  src/components/molecules/PostCard/index.tsx
  src/components/templates/MyPageTemplate/index.tsx
  src/components/templates/PostTemplates/index.tsx
Labels: Priority: High, Type: Bug, Type: Chore

#82 [Feat] 유저 검색 기능 추가
  src/apis/profile.ts
  src/components/molecules/Modal/UserSearchModal/index.tsx
  src/components/molecules/UserCard/index.tsx
  src/components/organisms/MessageRoomList/index.tsx
  src/components/templates/SearchModalTemplate/index.tsx
  src/types/user.ts
Labels: Priority: High, Type: Enhancement, Type: Style

#83 [Feat] 메일 인증 페이지 UI 및 기능 개발
  next.config.js
  src/apis/email.ts
  src/apis/instance.ts
  src/app/email-verification/error.tsx
  src/app/email-verification/layout.tsx
  src/app/email-verification/loading.tsx
  src/app/email-verification/page.tsx
  src/app/email-verification/send/page.tsx
  src/components/atoms/BackArrowContainer/index.tsx
  src/components/atoms/WhiteContainer/index.tsx
  src/components/organisms/SignupForm/index.tsx
  src/components/templates/EmailVerificationTemplate/SendVerificationEmailTemplate/index.tsx
  src/components/templates/EmailVerificationTemplate/VerificationEmailTemplate/index.tsx
  src/components/templates/MyPageTemplate/index.tsx
Labels: Priority: High, Type: Enhancement, Type: Style, Type: Chore

#85 [Feat] 스코어 이미지 모달 구현 및 적용
  src/components/molecules/Modal/ImageModal/index.tsx
  src/components/molecules/RecordCard/index.tsx
Labels: Priority: High, Type: Enhancement

#88 [Fix] Badge 마감 판단 로직 수정 및 점수, 별점 등록 버튼 표현 로직 수정
  src/components/atoms/Badge/index.tsx
  src/components/molecules/PostCard/index.tsx
  src/components/molecules/RecordCard/index.tsx
  src/components/molecules/RecordCardMember/index.tsx
  src/components/templates/ApplicantConfirmTemplate/index.tsx
  src/components/templates/PostTemplates/index.tsx
  src/utils/isPastTime.ts
Labels: Priority: High, Type: Bug

#90 [Feat] 볼링장 찾기 페이지 추가
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/molecules/KaKaoMap/index.tsx
  src/components/molecules/NavigationBar/index.tsx
  src/components/templates/SearchTemplate/index.tsx
Labels: Priority: High, Type: Enhancement, Type: Style

#84 [Fix] 별점 소수점 처리
  src/components/molecules/ApplicantBlock/index.tsx
  src/components/templates/MyPageTemplate/index.tsx
  src/components/templates/ProfileModalTemplate/index.tsx
Labels: Priority: Low, Type: Bug

#92 [Refactor] 허동혁 6, 7주차 피드백 반영
  src/components/atoms/RecordSummary/index.tsx
  src/components/molecules/PostList/index.tsx
  src/components/molecules/RecordSearchBar/index.tsx
  src/components/organisms/RecordCardList/index.tsx
  src/hooks/useIntersectionObserver.ts
  src/hooks/useRecordInfinityQuery.ts
Labels: Priority: Low, Type: Maintenance

#100 [Fix] 크램폴린 배포 환경에서 이미지 깨짐 버그 수정
  Dockerfile
  next.config.js
  src/utils/imageLoader.ts
Labels: Priority: High, Type: Bug, Type: Chore

#101 [Fix] 신청자 확인 모달 수락 후 반영되지 않던 버그 수정
  src/apis/applicant.ts
  src/components/molecules/ApplicantBlock/index.tsx
Labels: Priority: Low, Type: Bug

#105 [Feat] 서비스 이용 약관, 개인정보 수집 동의 링크 제거
  src/components/atoms/AuthCheckBox/index.tsx
Labels: Priority: Low, Type: Maintenance

#108 [Feat] 모바일 UI 남은부분 추가
  src/components/atoms/Button/index.tsx
  src/components/atoms/CircularProfileImage/index.tsx
  src/components/atoms/RecordSummary/index.tsx
  src/components/molecules/DatePicker/index.tsx
  src/components/molecules/Message/index.tsx
  src/components/molecules/MessageSubmit/index.tsx
  src/components/molecules/MiniProfile/index.tsx
  src/components/molecules/Modal/ImageModal/index.tsx
  src/components/molecules/RecordCard/index.tsx
  src/components/molecules/RecordCardMember/index.tsx
  src/components/molecules/RecordOverview/index.tsx
  src/components/molecules/RecordSearchBar/index.tsx
  src/components/molecules/ScoreInput/index.tsx
  src/components/molecules/SimpleDatePicker/index.tsx
  src/components/organisms/CreatePostForm/index.tsx
  src/components/organisms/MessageForm/index.tsx
  src/components/organisms/PostEditForm/index.tsx
  src/components/organisms/RecordCardList/index.tsx
  src/components/organisms/ScoreEditForm/index.tsx
  src/components/templates/ScoreEditTemplate/index.tsx
  src/components/templates/StarRatingTemplate/index.tsx
Labels: Priority: Medium, Type: Style

#109 [Feat] mutate 요청 에러 핸들링
  src/components/molecules/ApplicantBlock/index.tsx
  src/components/molecules/ApplyButton/index.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/CommentBlock/index.tsx
  src/components/molecules/Message/index.tsx
  src/components/molecules/MessageSubmit/index.tsx
  src/components/molecules/PostEditor/index.tsx
  src/components/molecules/ScoreInput/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/components/organisms/CreatePostForm/index.tsx
  src/components/organisms/MessageRoomList/index.tsx
  src/components/organisms/PostEditForm/index.tsx
  src/components/organisms/SigninForm/index.tsx
  src/components/organisms/SignupForm/index.tsx
  src/components/templates/ApplicantConfirmTemplate/index.tsx
  src/components/templates/MyPageTemplate/index.tsx
  src/components/templates/StarRatingTemplate/index.tsx
  src/hooks/useApiErrorToast.ts
  src/utils/getApiErrorMsg.ts
Labels: Priority: High, Type: Enhancement

#106 [Feat] 모달 suspense, errorBoundary 처리
  package-lock.json
  package.json
  src/components/atoms/ErrorBoundaryWithQuery/index.tsx
  src/components/atoms/SuspenseErrorBoundary/index.tsx
  src/components/molecules/Modal/ApplicantConfirmModal/index.tsx
  src/components/molecules/Modal/ErrorModal/index.tsx
  src/components/molecules/Modal/LoadingModal/index.tsx
  src/components/molecules/Modal/ModalLayout/index.tsx
  src/components/molecules/Modal/ProfileModal/index.tsx
  src/components/molecules/Modal/ScoreEditModal/index.tsx
  src/components/molecules/Modal/StarRatingModal/index.tsx
  src/components/molecules/Modal/UserSearchModal/index.tsx
  src/components/templates/ApplicantConfirmTemplate/index.tsx
  src/components/templates/ProfileModalTemplate/index.tsx
  src/components/templates/SearchModalTemplate/index.tsx
  src/components/templates/StarRatingTemplate/index.tsx
  src/hooks/useResetErrorWithQuery.ts
Labels: Priority: High, Type: Enhancement, Type: Chore

#104 [Feat] 전역 에러 핸들링
  src/app/create/loading.tsx
  src/app/email-verification/page.tsx
  src/app/email-verification/send/page.tsx
  src/app/error.tsx
  src/app/loading.tsx
  src/app/message/loading.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/loading.tsx
  src/app/mypage/page.tsx
  src/app/scoreboard/[scoreboard_user_id]/loading.tsx
  src/components/templates/ScoreEditTemplate/index.tsx
Labels: Priority: High, Type: Enhancement

#111 [Feat] 메인, 상세페이지 ssr 적용
  package-lock.json
  package.json
  src/apis/comment.ts
  src/app/page.tsx
  src/app/post/[id]/page.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/CommentBlock/index.tsx
  src/components/molecules/PostEditor/index.tsx
  src/components/molecules/PostList/HydratePostList/index.tsx
  src/components/molecules/PostList/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/components/templates/PostTemplates/HydratePostTemplates/index.tsx
  src/components/templates/PostTemplates/index.tsx
  src/utils/providers/queryClient.ts
  src/utils/providers/queryProvider.tsx
Labels: Priority: High, Type: Enhancement

#112 [Feat] Not-found 페이지 추가
  src/app/[...Not-found]/page.tsx
  src/app/not-found.tsx
Labels: Priority: Medium, Type: Enhancement

#113 [Feat] 페이지 단위 에러 핸들링 및 로딩 처리
  src/app/create/loading.tsx
  src/app/email-verification/page.tsx
  src/app/email-verification/send/page.tsx
  src/app/error.tsx
  src/app/loading.tsx
  src/app/message/loading.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/loading.tsx
  src/app/mypage/page.tsx
  src/app/post/[id]/edit/loading.tsx
  src/app/scoreboard/[scoreboard_user_id]/loading.tsx
  src/app/search/loading.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/molecules/Modal/UserSearchModal/index.tsx
  src/components/molecules/PostList/HydratePostList/index.tsx
  src/components/molecules/PostList/index.tsx
  src/components/molecules/RecordOverview/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/components/organisms/MessageForm/index.tsx
  src/components/organisms/MessageRoomList/index.tsx
  src/components/organisms/PostEditForm/index.tsx
  src/components/templates/DefaultLoadingUI/index.tsx
  src/components/templates/PostTemplates/index.tsx
  src/components/templates/SearchModalTemplate/index.tsx
  src/hooks/useRecordInfinityQuery.ts
  src/types/pageSearchParams.ts
Labels: Priority: High, Type: Bug, Type: Enhancement

#114 [Refactor] 일부 api 요청 staleTime, cacheTime Infinity 설정
  src/components/molecules/AuthButton/AuthUserProfile/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/components/templates/MyPageTemplate/index.tsx
  src/components/templates/ScoreEditTemplate/index.tsx
  src/hooks/useRegionQueries.ts
Labels: Priority: Low, Type: Maintenance

#115 [Design] 메일 인증 페이지 로딩 UI 적용 및 반응형 디자인 적용
  src/app/email-verification/send/page.tsx
  src/components/atoms/EmailAirplane/EmailAirplane.css
  src/components/atoms/EmailAirplane/index.tsx
  src/components/templates/EmailVerificationTemplate/SendVerificationEmailTemplate/index.tsx
  src/components/templates/EmailVerificationTemplate/VerificationEmailTemplate/index.tsx
Labels: Priority: Low, Type: Style

#116 [Refactor] 드롭다운 기능 개선
  src/components/atoms/Dropdown/index.tsx
Labels: Priority: Low, Type: Bug, Type: Maintenance

#117 [Fix] 버그 수정
  src/components/molecules/Modal/ImageModal/index.tsx
  src/components/molecules/RecordFilter/index.tsx
  src/components/molecules/ScoreInput/index.tsx
Labels: Priority: Medium, Type: Bug

#118 [Fix] 프로필 수정 닉네임 변경 없이 요청이 가능하도록 수정
  src/apis/profile.ts
  src/components/templates/MyPageTemplate/index.tsx
Labels: Priority: Low, Type: Bug

#119 [ Fix] 토큰 재발급 에러 처리
  src/apis/instance.ts
  src/components/organisms/SigninForm/index.tsx
Labels: Priority: High, Type: Bug

#120 [Docs] README 작성
  README.md
  docs/LogoTitle-Orange.png
Labels: Priority: High
