Repository Step3-kakao-tech-campus/Team3_FE, pull requests merged in 2023-10, with the labels that each got.

#23 [Refactor] : api 폴더 정리
  src/apis/district.ts
  src/apis/getCities.ts
  src/apis/getCountries.ts
  src/apis/getDistricts.ts
  src/apis/getPosts.ts
  src/apis/instance.ts
  src/apis/postRegisterPosts.ts
  src/apis/postUser.ts
  src/apis/posts.ts
  src/apis/sign.ts
  src/components/atoms/SearchedLocationDisplay/index.tsx
  src/components/molecules/DropdownBox/index.tsx
  src/components/molecules/NavigationBar/index.tsx
  src/components/molecules/PostList/index.tsx
  src/components/organisms/CreatePostForm/index.tsx
  src/components/organisms/SigninForm/index.tsx
  src/components/organisms/SignupForm/index.tsx
  src/stores/features/counterSlice.ts
Labels: Priority: Low, Type: Maintenance

#26 [Feat] 게시글 상세정보 페이지 UI 구현
  src/apis/instance.ts
  src/apis/posts.ts
  src/app/post/[id]/page.tsx
  src/components/atoms/Participant/index.tsx
  src/components/atoms/RoundImage/index.tsx
  src/components/molecules/DatePicker/index.tsx
  src/components/molecules/PostCard/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/components/templates/PostTemplates/index.tsx
  src/utils/formatDateToString.ts
Labels: Priority: High, Type: Maintenance, Type: Style

#28 [Fix] UTC시간을 한국시간으로 수정
  src/apis/posts.ts
  src/components/organisms/CreatePostForm/index.tsx
  src/utils/formatDateToString.ts
Labels: Priority: Medium, Type: Bug, Type: Maintenance

#29 [Refactor] 버튼 스타일 분리
  src/components/atoms/Button/index.tsx
  src/components/molecules/DatePicker/index.tsx
  src/components/molecules/NavigationBar/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/components/organisms/CreatePostForm/index.tsx
  src/components/organisms/SigninForm/index.tsx
  src/components/organisms/SignupForm/index.tsx
  src/components/templates/PostTemplates/index.tsx
Labels: Priority: Low, Type: Maintenance

#33 [Fix] 회원가입 모달 지역 선택 버그 수정
  src/components/organisms/SigninForm/index.tsx
  src/components/organisms/SignupForm/index.tsx
Labels: Priority: High, Type: Bug

#35 [Feat] 댓글 UI 및 기능 추가
  src/apis/comment.ts
  src/components/molecules/ChildComment/index.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/CommentSubmit/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/components/templates/PostTemplates/index.tsx
  src/hooks/useCommentsMutation.ts
  src/types/commentData.ts
Labels: Priority: High, Type: Enhancement, Type: Maintenance, Type: Style

#36 [Fix] Dropdown 버그 및 스타일 수정
  src/components/atoms/Dropdown/index.tsx
Labels: Type: Bug, Type: Style

#41 [Feat] 참여기록 페이지 UI 구현
  src/app/create/page.tsx
  src/app/post/[id]/page.tsx
  src/app/scoreboard/[user_id]/page.tsx
  src/components/atoms/BackArrowButton/index.tsx
  src/components/atoms/BackArrowContainer/index.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/RecordSummary/index.tsx
  src/components/molecules/MiniProfile/index.tsx
  src/components/molecules/RecordCard/index.tsx
  src/components/molecules/RecordCardMember/index.tsx
  src/components/molecules/RecordFilter/index.tsx
  src/components/molecules/RecordSearchBar/index.tsx
  src/components/organisms/CreatePostForm/index.tsx
  src/components/templates/PostTemplates/index.tsx
  src/components/templates/ProfileModalTemplate/index.tsx
  src/components/templates/ScoreboardTemplate/index.tsx
  src/types/recordData.ts
Labels: Priority: High, Type: Style

#45 [Refactor] 멘토님 피드백 적용
  src/components/atoms/AuthInput/index.tsx
  src/components/atoms/BlankBar/index.tsx
  src/components/atoms/Modal/index.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/InputBox/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/components/organisms/CreatePostForm/index.tsx
  src/components/organisms/SigninForm/index.tsx
Labels: Priority: Low, Type: Maintenance

#46 [Refactor] 5주차 피드백 반영
  src/components/atoms/BackArrowButton/index.tsx
  src/components/atoms/Dropdown/index.tsx
  src/components/atoms/SearchedLocationDisplay/index.tsx
  src/components/molecules/ApplicantBlock/index.tsx
  src/components/molecules/PostFilter/index.tsx
  src/components/molecules/PostList/index.tsx
  src/components/molecules/RecordSearchBar/index.tsx
  src/types/postSearchParam.ts
Labels: Priority: Low, Type: Maintenance

#43 [Feat] 댓글 수정 / 삭제 / 답글 달기 구현
  src/apis/comment.ts
  src/components/molecules/ChildComment/index.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/CommentBlock/index.tsx
  src/components/molecules/CommentSubmit/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/hooks/useCommentsMutation.ts
  src/hooks/useMutateWithQueryClient.ts
Labels: Priority: High, Type: Enhancement, Type: Maintenance, Type: Style

#62 [Feat] 토큰 재발급 로직 추가
  src/apis/auth.ts
  src/apis/authInstance.ts
  src/apis/instance.ts
  src/apis/sign.ts
  src/app/layout.tsx
  src/components/molecules/ApplyButton/index.tsx
  src/components/molecules/AuthButton/AuthUserProfile/index.tsx
  src/components/molecules/AuthButton/index.tsx
  src/components/molecules/NavigationBar/index.tsx
  src/components/molecules/PostList/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/components/organisms/SigninForm/index.tsx
  src/components/organisms/SignupForm/index.tsx
  src/stores/features/counterSlice.ts
  src/stores/hooks.ts
  src/stores/provider.tsx
  src/stores/store.ts
  src/utils/user.ts
Labels: Priority: High, Type: Enhancement, Type: Maintenance

#60 [Feat] 토스트 컴포넌트 추가
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/CommentBlock/index.tsx
  src/components/molecules/Toast/ToastItem/index.tsx
  src/components/molecules/Toast/index.tsx
  src/components/organisms/CommentForm/index.tsx
  src/hooks/useToast.ts
  src/stores/atoms/toastState.ts
  src/types/toast.ts
  src/utils/providers/queryProvider.tsx
  src/utils/providers/recoilRootProvider.tsx
Labels: Priority: Low, Type: Enhancement, Type: Maintenance, Type: Chore

#69 [Feat] 쪽지함 페이지 & 쪽지 대화 페이지 개발
  src/apis/message.ts
  src/app/message/[opponent_user_id]/page.tsx
  src/app/message/page.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/CheckBox/index.tsx
  src/components/atoms/CircularProfileImage/index.tsx
  src/components/molecules/Message/index.tsx
  src/components/molecules/MessageCard/index.tsx
  src/components/molecules/MessageSubmit/index.tsx
  src/components/molecules/SemiModal/ReconfirmModal/index.tsx
  src/components/molecules/SemiModal/index.tsx
  src/components/organisms/MessageForm/index.tsx
  src/components/organisms/MessageRoomList/index.tsx
  src/styles/globals.css
  src/types/message.ts
  src/utils/formatDateToString.ts
  src/utils/processString.ts
Labels: Priority: High, Type: Enhancement, Type: Maintenance, Type: Style

#70 [Feat] 프로필 모달 연결
  src/components/atoms/Modal/index.tsx
  src/components/molecules/ApplicantBlock/index.tsx
  src/components/molecules/AuthButton/AuthUserProfile/index.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/CommentBlock/index.tsx
  src/components/molecules/NavigationBar/index.tsx
  src/components/templates/PostTemplates/index.tsx
  src/components/templates/ProfileModalTemplate/index.tsx
Labels: Priority: Low, Type: Enhancement

#74 [Refactor] 프로필, 신청자 확인 모달 로직 변경
  src/app/@modal/(.)applicant_confirm/[post_id]/page.tsx
  src/app/@modal/(.)signin/page.tsx
  src/app/@modal/(.)signup/page.tsx
  src/app/@modal/(.)user_profile/[user_id]/page.tsx
  src/app/@modal/[...close_modal]/page.tsx
  src/app/layout.tsx
  src/components/atoms/ProfileLink/index.tsx
  src/components/molecules/ApplicantBlock/index.tsx
  src/components/molecules/ApplyButton/index.tsx
  src/components/molecules/AuthButton/AuthUserProfile/index.tsx
  src/components/molecules/ChildComment/index.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/CommentBlock/index.tsx
  src/components/molecules/Modal/ApplicantConfirmModal/index.tsx
  src/components/molecules/Modal/ProfileModal/index.tsx
  src/components/molecules/Modal/index.tsx
  src/components/templates/ApplicantConfirmTemplate/index.tsx
  src/components/templates/PostTemplates/index.tsx
  src/components/templates/ProfileModalTemplate/index.tsx
  src/stores/atoms/profileModalState.ts
Labels: Priority: Low, Type: Maintenance

#76 [Feat] 로딩 UI 적용
  src/app/create/loading.tsx
  src/app/message/loading.tsx
  src/app/page.tsx
  src/app/scoreboard/[scoreboard_user_id]/loading.tsx
  src/components/atoms/BackArrowButton/index.tsx
  src/components/molecules/PostList/index.tsx
  src/components/organisms/PostEditForm/index.tsx
  src/components/templates/PostTemplates/index.tsx
Labels: Priority: Low, Type: Bug, Type: Enhancement
