Repository Step3-kakao-tech-campus/Team3_FE, pull requests merged in 2023-09, with the labels that each got.

#6 Feat/navbar
  .eslintrc.json
  .github/ISSUE_TEMPLATE/기능-이슈.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  public/favicons/favicon.ico
  public/images/bowling_logo.png
  src/app/layout.tsx
  src/components/atoms/Background/index.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/InnerContainer/index.tsx
  src/components/molecules/NavigationBar/index.tsx
  tailwind.config.ts
Labels: Priority: High, Type: Maintenance, Type: Style, Type: Chore

#7 Feat/post card
  public/images/default_profile_image.png
  src/components/atoms/Badge/index.tsx
  src/components/molecules/PostCard/index.tsx
  src/types/PostData.ts
  src/utils/formatDateToString.ts
Labels: Priority: Medium, Type: Enhancement, Type: Style

#8 Feat/signup UI
  package-lock.json
  package.json
  src/app/@modal/(.)signin/page.tsx
  src/app/@modal/(.)signup/page.tsx
  src/app/@modal/default.tsx
  src/app/Signup/page.tsx
  src/app/default.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/signin/page.tsx
  src/components/atoms/AuthCheckBox/index.tsx
  src/components/atoms/AuthInput/index.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/Dropdown/index.tsx
  src/components/atoms/Modal/index.tsx
  src/components/molecules/DropdownBox/index.tsx
  src/components/molecules/InputBox/index.tsx
  src/components/molecules/NavigationBar/index.tsx
  src/utils/validation.ts
  tailwind.config.ts
Labels: Priority: High, Type: Enhancement, Type: Style
